### ISSUE TITLE
(Not issues, just request) Any chance of porting the module to Half-Life:Adrenaline Gamer 6.6?

### ISSUE THREAD

**Issue by Mehmet-I** [Garey27/hitbox_fixer#1]
Hello Bro,

I reviewed your work. You did a very good job. We have Half-Life servers with many of my friends. If you can port this module to Half-Life, we can use it on our servers.

I wish you good work.

Edit: Sorry, I saw version 1.4 on another forum. I think the new version has Half-Life support.
Many professional Half-Life players play the Adrenaline Gamer 6.6 mod. It would be great if the mod also supports Ag 6.6.

**Comment by Mehmet-I** [comment]
Sorry, I saw version 1.4 on another forum. I think the new version has Half-Life support.

**Comment by Garey27** [comment]
Hello! Does mod directory is the same as Half-Life? (/valve) If yes you can try 1.0.9 version

**Comment by Garey27** [comment]
Support for AG is added in 1.0.10
