### ISSUE TITLE
Не всегда работает фикс 

### ISSUE THREAD

**Issue by deniska21233** [Garey27/hitbox_fixer#10]
Стоит 2 сервера и без разница какая ось ядра не модифицирую 
Один на gcc rehlds 
второй rehlds официальный 
Так вот оба работают с параметрами sys_ticrate 1200 pingboost 4  на 5 герцовой вдс 
так же включена лага компенсация как говорил автор 
Так вот на высоком фпсе сервера не всегда работает фиксбокс стрелял в голову по пульке и урон не проходил хотя прицел был на голове 
Пожалуйста помогите решить проблему

**Comment by NortonnCommander** [comment]
Не уверен что дело в модуле, но подобное тоже замечаю, сервер классик (sys_ticrate 1080). Грешу на клиентский cl_cl/cl_lw или на пинг игрока 60-80, иногда когда должен попадать по хитбоксу головы, пули летят сквозь.

**Comment by Garey27** [comment]
Фикс обычно работает хорошо когда противник в движении, когда стоит все равно иногда ломаются в т.ч. из за вхблокера когда резко поступает информация о игроке а предыдущие состояния игрока не доступны из за отсутствия информации о игроках на клиенте из за чего происходит рассинхрон
