### ISSUE TITLE
hitbox 1.1.5 windows hlds 8684 crash!!!

### ISSUE THREAD

**Issue by Escap3d** [Garey27/hitbox_fixer#13]
https://www.mediafire.com/file/jeicdygdg8vpwrz/hlds_crash_20231119_104816.zip/file

**Comment by Escap3d** [comment]
windows rehlds working normaly...

**Comment by Garey27** [comment]
Does 1.1.4 works? I didn't change signature scan functions, its just experimental support for FireArms 3.0 mod.

**Comment by Escap3d** [comment]
> Does 1.1.4 works? I didn't change signature scan functions, its just experimental support for FireArms 3.0 mod.

no bro 1.1.4 also crash

**Comment by 175440** [comment]
Hello, something similar happens to me.
It doesn't load and leaves.
I'm trying to use it offline with bots. Failed to load game and I don't know the reason.
Thanks for the suggestions .

https://youtu.be/s8J38kxKNoo
