### ISSUE TITLE
Counter-Strike 1.6 

### ISSUE THREAD

**Issue by deNchj** [Garey27/hitbox_fixer#15]
How can we run ReHLDS as .dll directly in pro game match servers without amx_mods? I want to be able to use it when throwing 5-5 matches I want to fix hitbox I don't want to open it for a solo server, I want to open it while playing on community servers

**Comment by di57inct** [comment]
Why would u not want amx installed on a 5v5 server? Anyway, just install latest rehlds, latest metamod-r and this metamod plugin.

**Comment by deNchj** [comment]
I sent you a friend request on steam and if you accept, I'll ask you a question
