### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by OsweRRR** [Garey27/hitbox_fixer#2]
No me tomare la molestia de traducir a tu idioma, tu modulo no funciona y pienso que si no se corrige desde el cliente la correcion para server no va a funcionar.

https://www.youtube.com/watch?v=3oMR2kMacBQ

Tal vez me haya equivocado, si tu modulo realmente corrige algo deberias mencionarlo

**Comment by Garey27** [comment]
Hello! Which version do you use? Also does module is works? Can you send "meta list" and cvar value for hbf_enabled?

**Comment by Garey27** [comment]
Also this fix with hitboxes works only for clients with cl_lc/cl_lw 1 and sv_maxunlag 0.5 sv_unlag 1

**Comment by OsweRRR** [comment]
Miralo con tus propios ojos

https://www.youtube.com/watch?v=DofyJtx8WY0

**Comment by SmileYzn** [comment]
> Miralo con tus propios ojos
> 
> https://www.youtube.com/watch?v=DofyJtx8WY0

post meta list command output not the amxmodx version or amxx output.

meta list command!

**Comment by OsweRRR** [comment]
Probe en un server linux, parece funcionar algunas veces pero en windows mi pc es totalmente un fail

`L 04/18/2022 - 12:41:26: -------- Mapchange to cs_max --------

Executing AMX Mod X Configuration File
rehlds.cfg ejecutada con exito!.
meta list
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] WHBlocker        RUN   -    whblocker_mm.dll  v1.5.696  ini  Chlvl ANY
 [ 2] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.9.0.5  ini  Start ANY
 [ 3] Reunion          RUN   -    reunion_mm.dll    v0.1.0.9  ini  Start Never
 [ 4] Rechecker        RUN   -    rechecker_mm.dll  v2.5      ini  Chlvl ANY
 [ 5] HitBox Fix       RUN   -    hitbox_fix_mm.dl  v1.0.10   ini  Start ANY
5 plugins, 5 running`

**Comment by SmileYzn** [comment]
Try 1.0.4 version, i think that 1.0.10 is buggy duo new changes.

**Comment by Garey27** [comment]
Lot of updates since that issue.
