### ISSUE TITLE
version issue!

### ISSUE THREAD

**Issue by Escap3d** [Garey27/hitbox_fixer#22]
![Screenshot 2024-12-09 192917](https://github.com/user-attachments/assets/ec2fa4ac-3679-481c-9bfb-be1c71d42b6e)
plz correct build version

**Comment by Garey27** [comment]
Hello, i assume you using version from "test" tag, after proper tests i 'll will make proper tag ex:2.0.2 or something.

**Comment by Garey27** [comment]
@Escap3d Thank you, there was actually problem with Github Actions not setting version automatically, fixed.
