### ISSUE TITLE
2.0.3 crash dump

### ISSUE THREAD

**Issue by zik32** [Garey27/hitbox_fixer#26]
Program terminated with signal 11, Segmentation fault.
#0  0xb155f484 in StartFramePost() () from /home/server4342/game/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
#0  0xb155f484 in StartFramePost() () from /home/server4342/game/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
#1  0xb2bd4285 in api_caller_void_args_void(void const*, void const*) () from /home/server4342/game/./cstrike/addons/metamod/dlls/metamod.so
#2  0xb2bd3925 in main_hook_function_void(unsigned int, enum_api_t, unsigned int, void const*) () from /home/server4342/game/./cstrike/addons/metamod/dlls/metamod.so
#3  0xb2bd6dae in mm_StartFrame() () from /home/server4342/game/./cstrike/addons/metamod/dlls/metamod.so
#4  0xb67a825d in SV_Physics() () from /home/server4342/game/engine_i486.so
#5  0x00000000 in ?? ()
No symbol table info available.
L 12/18/2024 - 11:10:34: [REUNION]: HLTV (**.174.48.**) authorized as HLTV
L 12/18/2024 - 11:10:34: "HLTV<1><HLTV><>" connected, address "**.174.48.**:28115"
version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.14.0.839-dev
Build date: 15:25:19 Sep 25 2024 (3819)
Build from: https://github.com/dreamstalker/rehlds/commit/b29740c
meta version
Metamod v1.21p37  2013/05/30 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v37
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: May 30 2013, 11:41:16 EET (optimized)
meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] SafeNameAndChat  RUN   -    SafeNameAndChat.  v1.1      ini   ANY   ANY  
 [ 2] Reunion          RUN   -    reunion_mm_i386.  v0.1.0.1  ini   Start Never
 [ 3] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.9.0.5  ini   Start ANY  
 [ 4] HitBox Fix       RUN   -    hitbox_fix_mm_i3  v2.0.3    ini   Start ANY  
 [ 5] Accuracy Fix     RUN   -    accuracyfix_mm.s  v1.1.7    ini   ANY   ANY  
 [ 6] MySQL            RUN   -    mysql_amxx_i386.  v1.9.0.5  pl3   ANY   ANY  
 [ 7] Amxx Easy Http   RUN   -    easy_http_amxx_i  v1.4.0    pl3   ANY   ANY  
 [ 8] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.9.0.5  pl3   ANY   ANY  
 [ 9] CStrike          RUN   -    cstrike_amxx_i38  v1.9.0.5  pl3   ANY   ANY  
 [10] SQLite           RUN   -    sqlite_amxx_i386  v1.9.0.5  pl3   ANY   ANY  
 [11] ReAPI            RUN   -    reapi_amxx_i386.  v5.22.0.  pl3   ANY   Never
 [12] GeoIP            RUN   -    geoip_amxx_i386.  v1.9.0.5  pl3   ANY   ANY  
 [13] gRIP             RUN   -    grip_amxx_i386.s  v0.1.5 B  pl3   ANY   ANY  
13 plugins, 13 running
./hlds_run: line 272:  4026 Bus error               (core dumped) $HL_CMD

**Comment by laimiukas3** [comment]
try update metamod
https://github.com/rehlds/Metamod-R/releases/tag/1.3.0.149

**Comment by zik32** [comment]
GJ, fix
