### ISSUE TITLE
Half-Life Video

### ISSUE THREAD

**Issue by Mehmet-I** [Garey27/hitbox_fixer#3]
Hello Bro
Can you make a video for Half Life? To show what the module does.

**Comment by fred0r** [comment]
devs [vid](https://www.youtube.com/watch?v=gPCN_6aXl54)

**Comment by Mehmet-I** [comment]
We need half life video :)

**Comment by hajimura** [comment]
Half Life has the same problem demonstrated in the video

**Comment by 175440** [comment]
someone please teach us how to install it? video, notes or something

**Comment by fred0r** [comment]
@175440 - offtopic, but:
download from https://github.com/Garey27/hitbox_fixer/releases
add according to your need - here a example for linux to use with [metamod](https://github.com/theAsmodai/metamod-r/releases/tag/1.3.0.131), add
`linux addons/hitbox_fix/hitbox_fix_mm_i386.so` to `addons/metamod/plugins.ini`

**Comment by 175440** [comment]
Thanks for your answer, but: plugins.ini contains something else and what are the requirements for this mod... plis

**Comment by 175440** [comment]
@fred0r  Thanks for your answer, but: plugins.ini contains something else and what are the requirements for this mod... plis

**Comment by Garey27** [comment]
![photo_1_2023-11-18_07-09-31](https://github.com/Garey27/hitbox_fixer/assets/4866813/ab90e83e-0d99-4d17-9a80-13e23d534b67)
![photo_2_2023-11-18_07-09-31](https://github.com/Garey27/hitbox_fixer/assets/4866813/61805eda-43d2-4bf0-8698-dab93603de60)
