### ISSUE TITLE
Podbot compatibility

### ISSUE THREAD

**Issue by kavavps1** [Garey27/hitbox_fixer#6]
Hi, first of all great work, finally something what fixes these garbage hitboxes

But the problem is while some1's running podbots on his cs 1.6 server
While I'm trying to combine hitbox_fixer with podbots, the server crashes immediately after creating a bot. **(Segmentation Fault)**

`version :  48/1.1.2.7/Stdio 2537 secure  (10)`
REHLDS 3.8.0.723

after disabling the podbots plugin, everything runs fine

**Comment by Garey27** [comment]
@kavavps1 Hello! Which version of PODBot you are using?

**Comment by Garey27** [comment]
Fixed in 1.1.0.
