### ISSUE TITLE
FireArms 3.0 support

### ISSUE THREAD

**Issue by APGRoboCop** [Garey27/hitbox_fixer#8]
Hello is this plugin able to fix some hit reg or inaccurate hitbox issues for some other HL1 mods like FireArms 3.0 as well as some other 3rd Party Mods for HL1? If this plugin doesn't quite work for FA 3.0 let me know and maybe add support please? FA had some inaccurate problems since FA version 2.7 came out near 2003.

**Comment by APGRoboCop** [comment]
Update: I've managed to recompile the Linux version using CMake v3.18.4 and Make using GCC/G++ v10.2 I had to exclude the -static-intel as gave me some errors and the /mem/patternscan.cpp needed to include the cstdio header as my compiler couldn't find printf declared.

Fortunately have altering this issues I've now got hitbox_fix_mm_i386.so and I'm running some tests on FireArms 3.0.

**Comment by abecee** [comment]
Hi. Sorry if i interrupt but what is firearms ?

**Comment by APGRoboCop** [comment]
https://www.moddb.com/mods/firearms/downloads/firearms-30-full

Also after doing some tests and adding FA support for "firearms.so" and "fa_i386.so" my server gave me a crash with this error:

```
Thread 1 "hlds_linux" received signal SIGSEGV, Segmentation fault.
0xf04738ca in PlayerPreThinkPre(edict_s*) ()
```

I'm not sure how this occurred. What I did is added this in main.cpp under 'boot OnMetaAttach()`:

```
        else if (!strcmp(a, "firearms"))
		{
            game_library = "firearms.dll";
			linux_game_library = "fa_i386.so";
			g_eGameType = GT_Firearms;
		}
	}
	if (g_eGameType != GT_CZero && g_eGameType != GT_CStrike && g_eGameType != GT_HL1 && g_eGameType != GT_Firearms)
```

Along with removing -static-intel and adding "#include <cstdio.h>" in /mem/patternscan.cpp and "GT_Firearms" under "enum GameType_e" in precompiled.h

**Comment by Garey27** [comment]
Hello, sorry for long waiting answer, but can you test this version?
https://github.com/Garey27/hitbox_fixer/releases/tag/1.1.5

**Comment by Garey27** [comment]
@APGRoboCop Hello, sorry for waiting an answer, but can you test this version?
https://github.com/Garey27/hitbox_fixer/releases/tag/1.1.5

**Comment by APGRoboCop** [comment]
ive just installed HitBox_Fixer 1.1.5 for FA 3.0 it seems...to have improved the hit reg issues, but i think it maybe cos im using reHLDS along with MetaMod-P-APG-40 to enhance its performance

**Comment by Garey27** [comment]
You can try to compile old commit of ReHLDS and test with only two players with hbf_enabled 0/1
https://github.com/dreamstalker/rehlds/pull/490 to see if it really works. 
Should be similar to: https://github.com/Garey27/hitbox_fixer/issues/3#issuecomment-1817327845

**Comment by deNchj** [comment]
Does it work on cs 1.6 match servers? When throwing a 5v5 match
